services:
  postgres:
    image: postgres:alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: abdessamad
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: abdessamad_db
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - pg-net
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - pg-net
    ports:
      - "8080:80"
    depends_on:
      - postgres

networks:
  pg-net:
    driver: bridge

volumes:
  pg-data:
  pgadmin-data:
